package fr.maxlego08.text.font;

import fr.maxlego08.text.ZFontTransformation;
import fr.maxlego08.text.api.Alphabet;
import fr.maxlego08.text.api.FontTransformation;
import fr.maxlego08.text.api.TextGeneratorPlugin;
import fr.maxlego08.text.api.fonts.FontInfo;

import java.io.File;
import java.util.ArrayList;
import java.util.List;

/**
 * An alphabet which uses the letters of a {@code .ttf} file.
 *
 * <p>Nothing has to be declared by hand : the width of every character is taken from the font
 * itself and the letters are rendered by the resource pack generated by the plugin.</p>
 */
public class TtfAlphabet implements Alphabet {

    private final TextGeneratorPlugin plugin;
    private final String name;
    private final File file;
    private final TtfFont font;
    private final List<FontInfo> fontInfos;
    private final FontTransformation fontTransformation = new ZFontTransformation("", "", new ArrayList<>());

    public TtfAlphabet(TextGeneratorPlugin plugin, String name, File file, TtfFont font) {
        this.plugin = plugin;
        this.name = name;
        this.file = file;
        this.font = font;

        List<FontInfo> infos = new ArrayList<>();
        font.getGlyphs().values().forEach(glyph -> infos.add(new FontInfo(glyph.character(), glyph.advance())));
        this.fontInfos = infos;
    }

    public TtfFont getFont() {
        return this.font;
    }

    @Override
    public String getName() {
        return this.name;
    }

    @Override
    public File getFile() {
        return this.file;
    }

    @Override
    public List<FontInfo> getFontInfos() {
        return this.fontInfos;
    }

    @Override
    public FontTransformation getFontTransformation() {
        return this.fontTransformation;
    }

    @Override
    public int getTextLength(String content) {
        return this.plugin.getColorHelper().getTextWithoutColor(content).chars().map(character -> getLength((char) character)).sum();
    }

    @Override
    public int getLength(char c) {
        return this.font.getAdvance(c);
    }

    @Override
    public String transformChar(char c, int height) {
        return render(this.font, c);
    }

    /**
     * Renders a character with the given font.
     *
     * <p>The character is wrapped inside a {@code font} MiniMessage tag so the client uses the
     * glyph generated by the plugin instead of the vanilla one.</p>
     *
     * @param font      the font to use
     * @param character the character to render
     * @return the MiniMessage content of the character
     */
    public static String render(TtfFont font, char character) {

        if (character == '\n' || character == '\r') {
            return String.valueOf(character);
        }

        if (character != ' ' && !font.getGlyphs().containsKey(character)) {
            // The font does not contain this character, the vanilla one is used instead.
            return String.valueOf(character);
        }

        return "<font:" + font.getFontId() + ">" + escape(character) + "</font>";
    }

    private static String escape(char character) {

        if (character == '<') {
            return "\\<";
        }

        if (character == '\\') {
            return "\\\\";
        }

        return String.valueOf(character);
    }

    @Override
    public String toString() {
        return "TtfAlphabet{name=" + this.name + ", font=" + this.font.getName() + "}";
    }
}
