package fr.maxlego08.text.api.fonts;

import java.util.LinkedHashMap;
import java.util.Map;

/**
 * Helper used by the TTF font system.
 *
 * <p>The plugin generates its own resource pack for every {@code .ttf} file placed inside the
 * {@code plugins/zTextGenerator/fonts} folder. Inside that pack a special font called
 * {@code ztextgen:offsets} is created. This font only contains "space" glyphs, one per possible
 * offset in pixel, which allows the plugin to align texts without any external resource pack
 * plugin (ItemsAdder, Nexo, Oraxen, ...).</p>
 */
public final class TtfOffsets {

    /**
     * Namespace used by every resource generated by the plugin.
     */
    public static final String NAMESPACE = "ztextgen";

    /**
     * Identifier of the font which contains every offset glyph.
     */
    public static final String FONT_KEY = NAMESPACE + ":offsets";

    /**
     * Maximum offset, in pixels, that can be applied in one glyph.
     */
    public static final int MAX_PIXELS = 128;

    private static final char NEGATIVE_BASE = '\uE200';
    private static final char POSITIVE_BASE = '\uE300';

    private TtfOffsets() {
    }

    /**
     * Gets the character used to move the cursor by the given amount of pixels.
     *
     * @param pixels number of pixels, negative to move to the left
     * @return the character of the {@link #FONT_KEY} font
     */
    public static char charFor(int pixels) {
        int clamped = Math.max(-MAX_PIXELS, Math.min(MAX_PIXELS, pixels));

        if (clamped == 0) {
            return ' ';
        }

        return clamped < 0 ? (char) (NEGATIVE_BASE + (-clamped)) : (char) (POSITIVE_BASE + clamped);
    }

    /**
     * Gets the MiniMessage tag which moves the cursor by the given amount of pixels.
     *
     * @param pixels number of pixels, negative to move to the left
     * @return an empty string if pixels is 0, the MiniMessage tag otherwise
     */
    public static String offset(int pixels) {
        if (pixels == 0) {
            return "";
        }

        return "<font:" + FONT_KEY + ">" + charFor(pixels) + "</font>";
    }

    /**
     * Gets every advance declared inside the {@code ztextgen:offsets} font.
     *
     * @return the character to pixel mapping used to generate the resource pack
     */
    public static Map<Character, Integer> advances() {

        Map<Character, Integer> advances = new LinkedHashMap<>();

        for (int i = 1; i <= MAX_PIXELS; i++) {
            advances.put((char) (NEGATIVE_BASE + i), -i);
            advances.put((char) (POSITIVE_BASE + i), i);
        }

        return advances;
    }
}
