package fr.maxlego08.text.api.commands;

import org.bukkit.command.CommandSender;

import java.util.List;

@FunctionalInterface
public interface CollectionBiConsumer {

    /**
     * Accepts a CommandSender and an array of String arguments to
     * generate a list of strings.
     *
     * @param sender the CommandSender object to be processed
     * @param args   the array of String arguments to be processed
     * @return the list of strings generated by the consumer
     */
    List<String> accept(CommandSender sender, String[] args);

}
